version: 2

build:
  os: ubuntu-lts-latest
  tools:
    python: latest
  jobs:
    pre_create_environment:
      - asdf plugin add uv
      - asdf install uv latest
      - asdf global uv latest
    create_environment:
      - uv venv $READTHEDOCS_VIRTUALENV_PATH
    install:
      - >
        VIRTUAL_ENV=$READTHEDOCS_VIRTUALENV_PATH
        UV_CACHE_DIR=$READTHEDOCS_VIRTUALENV_PATH/../../uv_cache
        uv sync --active --locked --group=doc --no-install-project

sphinx:
  configuration: docs/conf.py
