version: 2

build:
  os: ubuntu-lts-latest
  tools:
    python: latest
  jobs:
    post_create_environment:
      - asdf plugin add uv
      - asdf install uv latest
      - asdf global uv latest
      # Turn `python -m pip` into `python -c pass`
      - truncate --size 0 $READTHEDOCS_VIRTUALENV_PATH/lib/python3*/site-packages/pip/__main__.py
      - VIRTUAL_ENV=$READTHEDOCS_VIRTUALENV_PATH uv pip install --upgrade sphinx
    post_install:
      - VIRTUAL_ENV=$READTHEDOCS_VIRTUALENV_PATH uv pip install -r docs/requirements.txt
