---
name: Check changelog

on:
  pull_request:
    branches: [main, dev, maint/*]
    types:
      - opened
      - reopened
      - labeled
      - unlabeled
      - synchronize

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check_change_log:
    name: Check changelog
    runs-on: ubuntu-slim
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          fetch-depth: 0
      - name: Check for changes in changelog
        env:
          BASE_REF: ${{ github.event.pull_request.base.ref }}
          NO_CHANGELOG_LABEL: ${{ contains(github.event.pull_request.labels.*.name, 'no changelog') }}
        run: .github/scripts/scriv_check.sh
        shell: bash
